### ISSUE TITLE
Kernel Bypass support?

### ISSUE THREAD

**Issue by sarsanaee** [epfl-dcsl/lancet-tool#16]
Hey,

Lancet looks like a promising tool, however, it doesn't seem to be inclusive enough. For instance, so many instrumentations these days are need to be done for dpdk applications. That would be awesome if this tool can support kernel bypass client and servers as well.

Thanks,
Alireza

**Comment by marioskogias** [comment]
Hi Alireza,

could you elaborate on your usecase? Why do you want to use a kernel bypass client? Lancet leverages hardware timestamping for accuracy and it depends on the linux kernel for robustness. A kernel bypass client might give you more throughput with less machines. I understand that.

**Comment by sarsanaee** [comment]
Hello Mario,

Here is the setup I'm considering.

![20200311_193224](https://user-images.githubusercontent.com/3644605/76412946-82ad5880-63cf-11ea-917c-24441a77950c.jpg)

Absolutely, I can get higher throughput with fewer machines. What I like about Lancet is the methodology that produces more promising results, and I was thinking of using same methodology for my experiments, however, it seems Lancet doesn't support the kernel bypass approach.

Is there any opportunity to adopt Lancet for kernel bypass experiments? Or we need a lot of development in that regard? I believe there might be a lot of development effort to support kernel bypass type of experiments with Lancet.

Thanks,
Alireza

**Comment by marioskogias** [comment]
You can easily reuse the coordinator (Golang) and the agent-manager (Python), but you have to write your own agent. The new DPDK agent has to respect the API with the agent-manager, but this won't be hard. I'd be happy to help you with that and accept a PR.

**Comment by sarsanaee** [comment]
Hey Mario

OK sounds good then, I'll take a look into this.

Thanks,
Alireza
